import pygame
# import tcod

pygame.init()

# game sizes
CAMERA_WIDTH = 800
CAMERA_HEIGHT = 600
CELL_WIDTH = 32
CELL_HEIGHT = 32

# FPS LIMIT
GAME_FPS = 60

# MAP LIMITATIONS
MAP_WIDTH = 50
MAP_HEIGHT = 50
MAP_MAX_NUM_ROOMS = 10
# MAP_MIN_NUM_ROOMS = 10
MAP_BORDER_WIDTH = 2
MAP_NUM_LEVELS = 2

# ROOM LIMITATIONS
ROOM_MAX_HEIGHT = 7
ROOM_MIN_HEIGHT = 3
ROOM_MAX_WIDTH = 5
ROOM_MIN_WIDTH = 3

# color definitions
COLOR_ALPHA = 150

COLOR_BLACK = (0, 0, 0)
COLOR_WHITE = (255, 255, 255)
COLOR_GREY = (100, 100, 100)
COLOR_DGREY = (50, 50, 50)
COLOR_RED = (255, 0, 0)
COLOR_GREEN = (0, 255, 0)

# game colors
COLOR_DEFAULT_BG = COLOR_GREY

# FONTS
FONT_TITLE_SCREEN = pygame.font.Font("data/fonts/joystix monospace.ttf", 26)
FONT_DEBUG_MESSAGE = pygame.font.Font("data/fonts/joystix monospace.ttf", 20)
FONT_MESSAGE_TEXT = pygame.font.Font("data/fonts/joystix monospace.ttf", 12)
FONT_CURSOR_TEXT = pygame.font.Font("data/fonts/joystix monospace.ttf", CELL_HEIGHT)

# DEPTHS
DEPTH_PLAYER = -100
DEPTH_CREATURE = 1
DEPTH_ITEM = 2
DEPTH_CORPSE = 100
DEPTH_BKGD = 150

# FOV SETTINGS
FOV_ALGO = 0
FOV_LIGHT_WALLS = True
TORCH_RADIUS = 10

# MESSAGE DEFAULTS
NUM_MESSAGES = 4
